tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8001

spring:
  profiles:
    active: debug  
  redis:
    host: http://127.0.0.1
    port: 6379
---
spring:
  profiles: debug
  datasource:
    username: ENC(rYQlY4txefMNxT8z1IcYhQ==)
    password: ENC(so1oBlRb8iDT8vPXEqW2ofp5fbc7ucK3)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(jyxB9umVO/85oeWdhyh2u21QLDcOH2rrXyZ2hlDgn+EXCDcTcG36Ck2dtoGOl7wKiXGf3Gc5S8OmcXaDZ/jWH8ByboXa/fYjkHXBEk/Lw4fTu//jJ0Lcit/Y8GbYHWHR8E1C8eUIe9LGMKzLjDC6qWbExYIzvBJxXclNvOVvvRYILnfhVAPUX08MDznZBqy17VK6pyNc3oYDH0KJvTTSqfhJrlFoMzGQAbLRDWgrNdZ+h/Q/w0z0orQTAN9my1MMS2J8X01qRbitnE25bYN/xs2X6v+CQSla8O7LXtAp4nD+V73zS6CJf0GLfivoOsKEHHVyjIZCQiZGYiUOOuhC+CQkZA6vHhuKLkl6bFTvKAclClICv1RNiwvo5uO3lIb1GsTiigh3YhMqVAKfRK7ZNUqbr4Kkn25NfLhUJQ2Z9wo77ry2kiI7APBCaxWplRiOxMQTSZ4McaRqOh868alUJrZlzm00bskh+aoAos7SHHkJPCKzexSzgmU7cB149Bku)
    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring:
  profiles: release
  datasource:
    username: ENC(1ROEV/vW4+4Gz6lbhTUaUQ==)
    password: ENC(5CsWG0MU2v7GmHpHYZrNo9BVeQuUZzOH)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(tyjJWL63kpx0Gt5yLgrqPW2Qd4t0jzPSvHQbZ1z4YHv5qFLkOV7xyFC4Xs0kl4EpXOk4V9U8cmkGzfB84oLMiWQ/6+U2q75OYG7wGCfuxYEzZ0piqQJUkNwnt/qfMXU+v7d0FcCeC0msErGsIt9xUvh9dKElAodtVa+gyXK/DEo1V083zYS9ikf4guIoFSVIc4/g/3/m/0Yclv4CpxTKNm+w9nuiYnFviUPlwikeFPGhNRKkTcSwp5EX5SRpEsMHmdi4p0SlZ2xbu2qGKf4htlVF8s2G5sujazVgs1I6swZgbkXQ44t3uNQfWDYCvcyR3hiKk82B72ctqG5v2scpytKqCUrR+yF6WqA+YRzILEmdqeMN9Kk8vui0M0ZhWAQ2JjpQDFPC29KYCOf4Z7Cfhvr8mz4z37T5v6hfqAt35faqYKMY6DPwiiqqKvraWMH5sFHxDw4ebdSDTLDDxKpsMjS5N4jAa5ai/QgEkCmYA8QniN2XLIS90EIq1+Pzl9Gv)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
---
security: 
  oauth2:
    client:
      auto-approve-scopes: ".*"    
jasypt:
  encryptor:
    bean: jasyptStringEncryptor      