tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8001

spring:
  profiles:
    active: release  
  redis:
    host: http://127.0.0.1
    port: 6379
---
spring:
  profiles: debug
  datasource:
    username: admin
    password: Rorlwlakfk18@
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@jakedbdb_high?TNS_ADMIN=C:/Users/iuh12/Downloads/wallet
    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring:
  profiles: release
  datasource:
    username: admin
    password: Rorlwlakfk18@
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@jakedbdb_high?TNS_ADMIN=./wallet
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
---
security: 
  oauth2:
    client:
      auto-approve-scopes: ".*"
    authorization:
      token-key-access: isAuthenticated()
      check-token-access: isAuthenticated()